### ISSUE TITLE
nvidia-drm.modeset=1 freezes X11 when multiple monitors are connected

### ISSUE THREAD

**Issue by ad-on-is** [NVIDIA/open-gpu-kernel-modules#217]
**NVIDIA Driver Version**
nvidia-dkms 515.43.04-1

**GPU**
- Lenovo Legion 5
- RTX 2060 mobile
- 1 Internal laptop monitor
- 1 external monitor connected via HDMI
- 2 external monitors connected via USB-C

**Describe the bug**
When setting `nvidia-drm.modeset=1` in GRUB and booting the PC with more than one external monitor connected (in my case 3 external monitors) the system would sometimes freeze when an X11 display-manager starts (sddm, lightdm, etc.). 

Prior to 515 this was always the case, now in 515 it only happens sometimes.

**To Reproduce**
- Set `nvidia-drm.modeset=1` in GRUB
- Have multiple monitors connected
- Boot
- When SDDM/LightDM starts, mouse and keyboard freeze.

**Expected behavior**
System should boot up fine

**Logs**
https://pastebin.com/sTY0dvEV

**Comment by amrit1711** [comment]
Thanks for reporting the issue. However after reading the issue description, it appears that you are having similar issue with Nvidia proprietary driver ( doesn't occurs only with open gpu kernel module components).  
If you think otherwise, please let us know.
Else I would request you to post such issues on Linux forum using below URL or report through email "linux-bugs@nvidia.com" where more generic linux issues are addressed and worked upon.
 
https://forums.developer.nvidia.com/c/gpu-graphics/145

**Comment by ad-on-is** [comment]
@amrit1711 I already posted in the developer-forums, a month or so ago, but no one responded there. I was hoping I could raise more awareness when filing an issue here.

**Comment by amrit1711** [comment]
Sure, I have acknowledged the issue over forum and we can communicate further over there.
Thanks.
