### ISSUE TITLE
cuEGLStreamProducerConnect returns error 801 on 525 series

### ISSUE THREAD

**Issue by qumaciel** [NVIDIA/open-gpu-kernel-modules#414]
### NVIDIA Open GPU Kernel Modules Version

525.60.11

### Does this happen with the proprietary driver (of the same version) as well?

Yes

### Operating System and Version

CachyOS

### Kernel Release

6.0.10-1-cachyos-pds

### Hardware: GPU

NVIDIA GeForce RTX 2060

### Describe the bug

The issue reported in the [forum](https://forums.developer.nvidia.com/t/cueglstreamproducerconnect-returns-error-801-on-525-53-driver/233610) is still present in 525.60.11 version.

### To Reproduce

- Install 525 series driver
- Install [nvidia-vaapi-driver](https://github.com/elFarto/nvidia-vaapi-driver)
- Try hardware acceleration on Firefox

### Bug Incidence

Always

### nvidia-bug-report.log.gz

[va.log](https://github.com/NVIDIA/open-gpu-kernel-modules/files/10106640/va.log)

### More Info

More info:

> The issue is happening with the nvidia-vaapi-driver, on [this 12](https://github.com/elFarto/nvidia-vaapi-driver/blob/dbfb6083809941c3f2257b5f402964fba55b6cfe/src/export-buf.c#L118) line, which is odd because that code has been working fine up to now.

> For reference, the nvidia-vaapi-driver issue is [here 12](https://github.com/elFarto/nvidia-vaapi-driver/issues/126).

**Comment by amrit1711** [comment]
@qumaciel 
Thanks for reporting issue to us. I have filed a bug internally for tracking purpose.
Since this issue is not limited to open GPU kernel modules, I will close this tread and request you to follow updates via bug or below DevTalk forum link.
https://forums.developer.nvidia.com/t/cueglstreamproducerconnect-returns-error-801-on-525-53-driver/233610/3
