### ISSUE TITLE
Please if possible allow the "Discussion" feature on github for this project.

### ISSUE THREAD

**Issue by Quardah** [NVIDIA/open-gpu-kernel-modules#44]
Hi.

As you might imagine many of us will be eyeing this project due to the potential impacts of its release.

It would be very productive for the community to have the "Discussion" feature activated for this project so people can openly share their questions and results with the work presented.

Thank you for considering.

**Comment by MilesBHuff** [comment]
Should help to reduce non-issue spam in the Issues section.

**Comment by shbaskaran** [comment]
Thanks for the suggestion, Quardah. I've tagged this as an enhancement and will consider with our project admins enabling discussions. As we started out, we wanted to take an incremental approach to enabling such features - to allow us to get settled with GitHub, and gauge interest and response from the community.

**Comment by AaronWebster** [comment]
I think this is an excellent suggestion. As with any codebase that's been developed over many years, it's useful to have a place to have such discussions. For example, I just read an issue or someone was confused about naming conventions... Since most of us were invited when decisions were being made, sharing that knowledge gets you into the right mindset.

**Comment by shbaskaran** [comment]
The feature was enabled. See you there! :)
