### ISSUE TITLE
Null pointer dereference in `nv-pci.c`

### ISSUE THREAD

**Issue by qarmin** [NVIDIA/open-gpu-kernel-modules#57]
**NVIDIA Driver Version**
Git

https://github.com/NVIDIA/open-gpu-kernel-modules/blob/69791e9bf5161c786d620312fd6396756c37cff9/kernel-open/nvidia/nv-pci.c#L708-L716

`nvl->minor_num` is used if `nvl` is null

**Comment by amrit1711** [comment]
Thanks qarmin for highlighting the bug, I have filed a bug 3643046 internally for tracking purpose.

**Comment by sickcodes** [comment]
May as well track it externally 🎉 nice find

**Comment by ValZapod** [comment]
Oh, classic.

https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#232

**Indirection through a null pointer is not undefined behavior**, there is an open issue in the standard.  Well described here: https://stackoverflow.com/questions/28482809/c-access-static-members-using-null-pointer

What is much more funny is this in the file, since that is always true, change to &&:
https://github.com/NVIDIA/open-gpu-kernel-modules/blob/69791e9bf5161c786d620312fd6396756c37cff9/kernel-open/nvidia/nv-pci.c#L102

**Comment by PAR2020** [comment]
Resolved in PR #61
